- default:
  - Curriculum Vitae: cv

- Robotics Projects:
  - CWRUcam: cwrucam
  - CWRU ROS package: cwru_ros_pkg
  - IGVC: igvc
  - Precision Navigation: precision_navigation
  - Smart Wheelchair: smart_wheelchair
  - Course Projects: course_projects

#- Toys:    
#  - Art Project 1: art_project_1
#  - Artack: artack
#  - Bungie Chopper/Elite Bungie Chopper Squadron: bungie_chopper
#  - gw0rp: gw0rp
#  - Escort Wing: escort_wing
#  - Splatterboard: splatterboard

#- Code:  
# - JTrie: http://www.github.com/irskep/jtrie
# - Regex compiler: http://www.github.com/irskep/regex_compiler
#  - T-Reg: http://www.github.com/irskep/T-Reg

- Social:
  - Github: https://github.com/ericperko
  - ROS Answers: http://answers.ros.org/users/14/eric-perko/
  - ROS Community Involvement: ros_contributions
  - Stack Overflow: http://stackoverflow.com/users/130251/eric-perko 
  - Hacker News: http://news.ycombinator.com/user?id=wisesage5001
